name: HardcorePlus
version: 0.3-alpha
description: Harding the survival mode
author: Henry Barreto
website: https://github.com/henrybarreto/HardcorePlus
main: dev.henrybarreto.hardcoreplus.HardcorePlus